name: jfkdev
description: Portfolio site for Jeroen Meijer. Only works on web.

version: 1.0.0+1

environment:
  sdk: ">=2.7.1 <3.0.0"
  flutter: 1.17.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ^3.0.3
  yaml: ^2.2.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - config.yaml
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons/AppIcons.ttf
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans/Product-Sans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Product-Sans/Product-Sans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Product-Sans/Product-Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Product-Sans/Product-Sans-Bold-Italic.ttf
          weight: 700
          style: italic
    - family: Fira Code
      fonts:
        - asset: assets/fonts/Fira-Code/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/Fira-Code/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fira-Code/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fira-Code/FiraCode-Bold.ttf
          weight: 700
