name: jfkdev
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  get_it: ^2.0.1
  yaml: ^2.1.16

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

flutter:
  assets:
    - web/assets/config.yaml
  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/Fira Code/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/Fira Code/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fira Code/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fira Code/FiraCode-Bold.ttf
          weight: 700
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans/Product Sans Regular.ttf
          weight: 400
        - asset: assets/fonts/Product Sans/Product Sans Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Product Sans/Product Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Product Sans/Product Sans Bold Italic.ttf
          weight: 700
          style: italic
    - family: AppIcons
      fonts:
        - asset: assets/fontsAppIcons/AppIcons.ttf

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
